# Generated by Django 5.0.6 on 2026-09-03 10:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('is_weekly_off', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rostered_assignments', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING_PEER', 'Awaiting Peer Acceptance'), ('PENDING_MANAGER', 'Awaiting Manager Approval'), ('APPROVED', 'Approved & Rosters Swapped'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Requester')], default='PENDING_PEER', max_length=20)),
                ('peer_responded_at', models.DateTimeField(blank=True, null=True)),
                ('manager_action_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_swaps', to='employees.employee')),
                ('requested_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_swap_requests', to='employees.employee')),
                ('requested_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_swaps', to='shifts.shiftroster')),
                ('requesting_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_swap_requests', to='employees.employee')),
                ('requesting_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_swaps', to='shifts.shiftroster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('break_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('half_day_minimum_hours', models.DecimalField(decimal_places=2, default=Decimal('4.50'), max_digits=4)),
                ('full_day_minimum_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='shiftroster',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='shifts.shifttype'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftroster',
            unique_together={('employee', 'date')},
        ),
    ]
