# Generated by Django 5.0.6 on 2026-09-03 10:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('current_company', models.CharField(blank=True, max_length=255)),
                ('current_designation', models.CharField(blank=True, max_length=255)),
                ('total_experience_years', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('current_ctc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_ctc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('source', models.CharField(choices=[('PORTAL', 'Company Career Portal'), ('LINKEDIN', 'LinkedIn Sourced'), ('REFERRAL', 'Internal Employee Referral'), ('AGENCY', 'Recruitment Agency'), ('CAMPUS', 'Campus Drive'), ('OTHER', 'Other Channel')], default='PORTAL', max_length=20)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='organizations.organization')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_candidates', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('location_room', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('interviewers', models.ManyToManyField(related_name='scheduled_interviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_score', models.PositiveSmallIntegerField(default=3)),
                ('communication_score', models.PositiveSmallIntegerField(default=3)),
                ('culture_fit_score', models.PositiveSmallIntegerField(default=3)),
                ('overall_score', models.PositiveSmallIntegerField(default=3)),
                ('recommendation', models.CharField(choices=[('STRONG_HIRE', 'Strong Hire'), ('HIRE', 'Hire'), ('NEUTRAL', 'Neutral / Borderline'), ('DO_NOT_HIRE', 'Do Not Hire')], default='HIRE', max_length=20)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('summary_comments', models.TextField()),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='employees.employee')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='recruitment.interviewschedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_REVIEW', 'In Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offer Extended'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by Candidate')], default='IN_REVIEW', max_length=20)),
                ('overall_rating', models.PositiveSmallIntegerField(default=0)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.jobapplication'),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variable_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sign_on_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('joining_date', models.DateField()),
                ('offer_expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Executive Approval'), ('SENT', 'Offer Sent to Candidate'), ('ACCEPTED', 'Accepted by Candidate'), ('DECLINED', 'Declined by Candidate'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20)),
                ('special_terms', models.TextField(blank=True)),
                ('offer_letter_document', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='recruitment.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('number_of_openings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open & Active'), ('ON_HOLD', 'On Hold'), ('FILLED', 'Position Filled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level (0-2 yrs)'), ('MID', 'Mid Level (2-5 yrs)'), ('SENIOR', 'Senior Level (5-8 yrs)'), ('LEAD', 'Lead / Principal (8+ yrs)'), ('EXECUTIVE', 'Executive (12+ yrs)')], default='MID', max_length=20)),
                ('min_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('target_hire_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to='organizations.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to='organizations.department')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to='organizations.employmenttype')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_requisitions', to='employees.employee')),
                ('job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to='organizations.joblevel')),
                ('lead_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_requisitions', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requisitions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobrequisition'),
        ),
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_terminal', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_stages', to='organizations.organization')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='recruitment.recruitmentstage'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('requisition', 'candidate')},
        ),
    ]
