# Generated by Django 5.0.6 on 2026-09-03 10:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('min_base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mid_base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('target_annual_bonus_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('job_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='organizations.joblevel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='organizations.organization')),
            ],
            options={
                'ordering': ['job_level__rank_order', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning / Allowance'), ('DEDUCTION', 'Deduction / Withholding')], default='EARNING', max_length=20)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Flat Amount'), ('PERCENTAGE_BASIC', 'Percentage of Basic Pay'), ('FORMULA', 'Custom Formula Calculation')], default='FIXED', max_length=30)),
                ('percentage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_statutory', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='organizations.organization')),
            ],
            options={
                'ordering': ['component_type', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
