# Generated by Django 5.0.6 on 2026-09-03 10:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('self_review_deadline', models.DateField()),
                ('manager_review_deadline', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_cycles', to='organizations.organization')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Operational Excellence', max_length=100)),
                ('target_date', models.DateField()),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Strategic')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed / Achieved'), ('BEHIND', 'Behind Schedule')], default='IN_PROGRESS', max_length=20)),
                ('key_metric', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='organizations.organization')),
            ],
            options={
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Self-Review Pending'), ('SUBMITTED_SELF', 'Self-Review Submitted - Awaiting Manager'), ('MANAGER_EVALUATED', 'Manager Review Completed'), ('CALIBRATED', 'Final Calibrated & Closed')], default='DRAFT', max_length=30)),
                ('self_achievements', models.TextField(blank=True)),
                ('self_areas_for_growth', models.TextField(blank=True)),
                ('self_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Needs Immediate Improvement'), (2, '2 - Partially Meets Expectations'), (3, '3 - Fully Meets Expectations (Strong Contributor)'), (4, '4 - Exceeds Expectations (High Impact)'), (5, '5 - Exceptional / Role Model (Top 5%)')], null=True)),
                ('manager_feedback', models.TextField(blank=True)),
                ('manager_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Needs Immediate Improvement'), (2, '2 - Partially Meets Expectations'), (3, '3 - Fully Meets Expectations (Strong Contributor)'), (4, '4 - Exceeds Expectations (High Impact)'), (5, '5 - Exceptional / Role Model (Top 5%)')], null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('recommended_bonus_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='performance.appraisalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_appraisals', to='employees.employee')),
            ],
            options={
                'ordering': ['-cycle__start_date', 'employee__first_name'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
