# Generated by Django 5.0.6 on 2026-09-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('reason', models.CharField(choices=[('RESIGNATION', 'Voluntary Resignation'), ('CAREER_GROWTH', 'Better Opportunity'), ('PERSONAL', 'Personal / Health Reasons'), ('TERMINATION', 'Company Termination'), ('RETIREMENT', 'Retirement'), ('CONTRACT_END', 'End of Fixed-Term Contract')], default='RESIGNATION', max_length=30)),
                ('detailed_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated / Notice Serving'), ('CLEARANCE_PENDING', 'Clearances In Progress'), ('READY_FOR_EXIT', 'Clearances Complete - Ready for Final Settlement'), ('COMPLETED', 'Offboarding Complete & Exited'), ('CANCELLED', 'Resignation Withdrawn / Cancelled')], default='INITIATED', max_length=30)),
                ('is_eligible_for_rehire', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_workflow', to='employees.employee')),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_over_responsibilities', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('target_completion_date', models.DateField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='IN_PROGRESS', max_length=20)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buddies', to='employees.employee')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_workflow', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='HR', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_tasks', to='employees.employee')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='onboarding.employeeonboarding')),
            ],
            options={
                'ordering': ['due_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HR', 'HR Documentation & Verification'), ('IT', 'IT Infrastructure & Access Provisioning'), ('FACILITIES', 'Facilities, Desk & Badge'), ('TRAINING', 'Orientation & Policy Training'), ('MANAGER', 'Manager Introduction & Goal Setting')], default='HR', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('due_day_offset', models.IntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('assignee_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='onboarding.onboardingtemplate')),
            ],
            options={
                'ordering': ['due_day_offset', 'title'],
            },
        ),
        migrations.AddField(
            model_name='employeeonboarding',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.onboardingtemplate'),
        ),
        migrations.CreateModel(
            name='OffboardingClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('IT', 'IT Assets & System Accounts Deactivation'), ('FINANCE', 'Finance & Payroll Clearance (Loans / Advance)'), ('FACILITIES', 'Facilities ID Badge & Access Card Return'), ('HR', 'HR Exit Documentation & Statutory Forms'), ('DEPT', 'Departmental Knowledge Transfer & Project Handover')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Clearance'), ('APPROVED', 'Approved & Cleared'), ('REJECTED', 'Issues Flagged / Deductions Required')], default='PENDING', max_length=20)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('recoverable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comments', models.TextField(blank=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_clearances', to='employees.employee')),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='onboarding.employeeoffboarding')),
            ],
            options={
                'unique_together': {('offboarding', 'department')},
            },
        ),
    ]
