# Generated by Django 5.0.6 on 2026-09-03 10:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('status', models.CharField(choices=[('PRESENT', 'Present (Full Day)'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'Approved Leave'), ('HOLIDAY', 'Company Holiday'), ('WEEKLY_OFF', 'Weekly Off')], default='PRESENT', max_length=20)),
                ('is_late_entry', models.BooleanField(default=False)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('is_regularized', models.BooleanField(default=False)),
                ('clock_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('clock_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('clock_in_device', models.CharField(blank=True, max_length=255)),
                ('clock_out_device', models.CharField(blank=True, max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date', 'employee__first_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_clock_in', models.TimeField()),
                ('requested_clock_out', models.TimeField()),
                ('reason', models.CharField(max_length=255)),
                ('detailed_explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Record Updated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver_comments', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_regularizations', to='employees.employee')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to='attendance.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_working_days', models.PositiveSmallIntegerField(default=22)),
                ('present_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('absent_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('leave_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('holidays', models.PositiveSmallIntegerField(default=0)),
                ('weekly_offs', models.PositiveSmallIntegerField(default=8)),
                ('late_entries_count', models.PositiveSmallIntegerField(default=0)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_locked_for_payroll', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance_summaries', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance_summaries', to='organizations.organization')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
