# Generated by Django 5.0.6 on 2026-09-03 10:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition_number', models.CharField(max_length=50, unique=True)),
                ('purpose', models.CharField(choices=[('CLIENT_MEETING', 'Client Onsite Meeting / Pitch'), ('CONFERENCE', 'Industry Conference / Summit'), ('INTERNAL_TRANSFER', 'Internal Branch Audit / Transfer'), ('TRAINING', 'Technical Training Workshop')], default='CLIENT_MEETING', max_length=30)),
                ('description', models.TextField()),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('advance_amount_requested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_TRAVEL_DESK', 'Pending Travel Desk Booking'), ('BOOKED', 'Itinerary Booked & Confirmed'), ('COMPLETED', 'Travel Completed - Awaiting Settlement'), ('SETTLED', 'Expenses Reconciled & Closed'), ('REJECTED', 'Rejected')], default='PENDING_MANAGER', max_length=25)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('itinerary_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travels', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requisitions', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requisitions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-departure_date'],
            },
        ),
    ]
