# Generated by Django 5.0.6 on 2026-09-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('HEADCOUNT', 'Headcount & Demographics Analysis'), ('PAYROLL', 'Payroll Expenditure & Statutory Deductions'), ('ATTENDANCE', 'Attendance, Overtime & Leave Utilization'), ('RECRUITMENT', 'Recruitment ATS Funnel & Velocity'), ('PERFORMANCE', 'Performance Ratings & OKR Progress')], max_length=30)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily Automated Snapshot'), ('WEEKLY', 'Weekly Summary Digest'), ('MONTHLY', 'Monthly Financial & Workforce Report'), ('QUARTERLY', 'Quarterly Executive Review')], default='MONTHLY', max_length=20)),
                ('recipients_emails', models.TextField(help_text='Comma-separated email addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
