# Generated by Django 5.0.6 on 2026-09-03 10:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_pay_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('special_allowance_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('provident_fund_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('professional_tax_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('cycle_type', models.CharField(choices=[('MONTHLY', 'Monthly Calendar Cycle'), ('BI_WEEKLY', 'Bi-Weekly (Every 2 Weeks)'), ('SEMI_MONTHLY', 'Semi-Monthly (Twice a Month)')], default='MONTHLY', max_length=20)),
                ('start_day', models.PositiveSmallIntegerField(default=1)),
                ('end_day', models.PositiveSmallIntegerField(default=30)),
                ('payout_day', models.PositiveSmallIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_cycles', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_employees_count', models.PositiveIntegerField(default=0)),
                ('total_gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_employer_contributions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Calculating'), ('UNDER_REVIEW', 'Under Finance Review'), ('APPROVED', 'Approved by Executive'), ('LOCKED', 'Finalized & Locked for Disbursal'), ('DISBURSED', 'Funds Disbursed to Bank'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('run_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='organizations.organization')),
                ('payroll_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollcycle')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payroll_runs', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('organization', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payslip_number', models.CharField(max_length=50, unique=True)),
                ('working_days', models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=4)),
                ('payable_days', models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=4)),
                ('loss_of_pay_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bonus_incentives', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('provident_fund_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('medical_insurance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated & Verified'), ('PUBLISHED', 'Published to Employee Self-Service'), ('PAID', 'Paid / Disbursed')], default='GENERATED', max_length=20)),
                ('payment_method', models.CharField(default='DIRECT_DEPOSIT', max_length=50)),
                ('bank_account_masked', models.CharField(blank=True, max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-payroll_run__year', '-payroll_run__month', 'employee__first_name'],
            },
        ),
    ]
