# Generated by Django 5.0.6 on 2026-09-03 10:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('HEALTH_INSURANCE', 'Comprehensive Health Insurance'), ('DENTAL_VISION', 'Dental & Vision Care'), ('RETIREMENT_401K', '401(k) / Provident Fund Match'), ('LIFE_DISABILITY', 'Life & Disability Insurance'), ('WELLNESS_STIPEND', 'Wellness & Gym Stipend'), ('MEAL_VOUCHER', 'Meal & Nutrition Allowance')], max_length=30)),
                ('provider_name', models.CharField(max_length=150)),
                ('employer_monthly_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('employee_monthly_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('terms_document', models.FileField(blank=True, null=True, upload_to='benefits/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_plans', to='organizations.organization')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Covered'), ('PENDING_APPROVAL', 'Pending Enrollment Review'), ('OPTED_OUT', 'Opted Out by Employee'), ('TERMINATED', 'Coverage Terminated')], default='ACTIVE', max_length=20)),
                ('nominee_name', models.CharField(blank=True, max_length=150)),
                ('nominee_relationship', models.CharField(blank=True, max_length=50)),
                ('custom_employee_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='employees.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_employees', to='benefits.benefitplan')),
            ],
            options={
                'ordering': ['-enrolled_date'],
                'unique_together': {('employee', 'plan')},
            },
        ),
    ]
