# Generated by Django 5.0.6 on 2026-09-03 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other / Prefer not to say')], default='MALE', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('joining_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('employment_status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('SELECTED', 'Selected'), ('OFFER_SENT', 'Offer Sent'), ('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('ACTIVE', 'Active Employee'), ('CONFIRMED', 'Confirmed'), ('NOTICE_PERIOD', 'Notice Period'), ('EXITED', 'Exited'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=30)),
                ('is_manager', models.BooleanField(default=False)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent Address'), ('CURRENT', 'Current / Residential Address')], default='CURRENT', max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['address_type'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('ifsc_swift_code', models.CharField(max_length=50)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(default='Checking', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_diploma', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_percentage', models.CharField(blank=True, max_length=50)),
                ('activities', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLifecycleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('SELECTED', 'Selected'), ('OFFER_SENT', 'Offer Sent'), ('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('ACTIVE', 'Active Employee'), ('CONFIRMED', 'Confirmed'), ('NOTICE_PERIOD', 'Notice Period'), ('EXITED', 'Exited'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired')], max_length=30)),
                ('to_status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('SELECTED', 'Selected'), ('OFFER_SENT', 'Offer Sent'), ('ONBOARDING', 'Onboarding'), ('PROBATION', 'Probation'), ('ACTIVE', 'Active Employee'), ('CONFIRMED', 'Confirmed'), ('NOTICE_PERIOD', 'Notice Period'), ('EXITED', 'Exited'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired')], max_length=30)),
                ('transition_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-transition_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePastExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_description', models.TextField(blank=True)),
                ('leaving_reason', models.CharField(blank=True, max_length=255)),
                ('reference_contact', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert / Lead')], default='INTERMEDIATE', max_length=20)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('is_certified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['skill__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatutoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID / SSN Card'), ('DRIVING_LICENSE', 'Driver License'), ('TAX_CARD', 'Tax / PAN Card'), ('EDUCATION_CERT', 'Degree / Educational Certificate'), ('EXPERIENCE_LETTER', 'Relieving / Experience Letter'), ('OTHER', 'Other Identification')], max_length=30)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pan_ssn_number', models.CharField(max_length=50)),
                ('tax_regime', models.CharField(choices=[('NEW', 'New Simplified Tax Regime'), ('OLD', 'Old Tax Regime with Deductions')], default='NEW', max_length=20)),
                ('pf_uan_number', models.CharField(blank=True, max_length=50)),
                ('esic_number', models.CharField(blank=True, max_length=50)),
                ('is_tax_exempt', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
