# Generated by Django 5.0.6 on 2026-09-03 10:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('requires_receipt', models.BooleanField(default=True)),
                ('max_limit_per_claim', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted / Awaiting Manager'), ('MANAGER_APPROVED', 'Approved by Manager - Awaiting Finance'), ('FINANCE_APPROVED', 'Approved by Finance - Queued for Payout'), ('PAID', 'Reimbursed & Paid'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('manager_action_date', models.DateTimeField(blank=True, null=True)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='employees.employee')),
                ('finance_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_claims', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='organizations.organization')),
                ('reviewed_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviewed_claims', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expensecategory')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expenseclaim')),
            ],
            options={
                'ordering': ['expense_date'],
            },
        ),
    ]
